# This is a basic workflow to help you get started with Actions

name: django-foresight-python

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          sudo apt install libmemcached-dev
          cd tests
          python -m pip install --upgrade pip
          pip install pytest
          python -m pip install -e ..
          python -m pip install -r requirements/py3.txt
      - name: Install Thundra Python Agent
        uses: thundra-io/thundra-foresight-python-action@action-experiment
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}      
      - name: Run checks
        run: |
          cd tests
          ./runtests.py
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_DEBUG_ENABLE: true

