name: django-foresight-python
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system requirements
        run: |
          sudo apt-get install -y --no-install-recommends unixodbc-dev # required for pyodbc
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get -qq update
          sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17
      - name: Install Python dependencies
        run: |
          cd tests
          python -m pip install --upgrade pip
          pip install pytest
          python -m pip install -e ..
          python -m pip install -r requirements/py3.txt
      - name: Install Thundra Python Agent
        uses: thundra-io/thundra-foresight-python-action@action-experiment
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}      
      - name: Run checks
        run: |
          cd tests
          ./runtests.py
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_DEBUG_ENABLE: true
